package com.example.testta;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

public class Filter3 {

    public String transliterasi(String text){

        String f3=text;
        text = f3
                .replace("1B00","m")
                .replace("1B01","ng")
                .replace("1B02","ng")
                .replace("1B03","r")
                .replace("1B04","h")
                .replace("1B05","a")
                .replace("1B06","ā")
                .replace("1B07","i")
                .replace("1B08","ī")
                .replace("1B09","u")
                .replace("1B0A","ū")
                .replace("1B0B","rě")
                .replace("1B0C","rö")
                .replace("1B0D","lě")
                .replace("1B0E","lö")
                .replace("1B0F","e")
                .replace("1B10","ai")
                .replace("1B11","o")
                .replace("1B12","au")
                .replace("1B13","ka")
                .replace("1B14","kha")
                .replace("1B15","ga")
                .replace("1B16","gha")
                .replace("1B17","nga")
                .replace("1B18","ca")
                .replace("1B19","cha")
                .replace("1B1A","ja")
                .replace("1B1B","jha")
                .replace("1B1C","nya")
                .replace("1B1D","ţa")
                .replace("1B1E","ţha")
                .replace("1B1F","ḍa")
                .replace("1B20","ḍha")
                .replace("1B21","ņa")
                .replace("1B22","ta")
                .replace("1B23","tha")
                .replace("1B24","da")
                .replace("1B25","dha")
                .replace("1B26","na")
                .replace("1B27","pa")
                .replace("1B28","pha")
                .replace("1B29","ba")
                .replace("1B2A","bha")
                .replace("1B2B","ma")
                .replace("1B2C","ya")
                .replace("1B2D","ra")
                .replace("1B2E","la")
                .replace("1B2F","wa")
                .replace("1B30","şa")
                .replace("1B31","śa")
                .replace("1B32","sa")
                .replace("1B33","ha")
                .replace("1B34","")
                .replace("1B35","ā")
                .replace("1B36","i")
                .replace("1B37","ī")
                .replace("1B38","u")
                .replace("1B39","ū")
                .replace("1B3A","rě")
                .replace("1B3B","rö")
                .replace("1B3C","lě")
                .replace("1B3D","lö")
                .replace("1B3E","e")
                .replace("1B3F","ai")
                .replace("1B40","o")
                .replace("1B41","au")
                .replace("1B42","ě")
                .replace("1B43","ö")
                .replace("1B44","")
                .replace("1B45","")
                .replace("1B46","")
                .replace("1B47","")
                .replace("1B48","")
                .replace("1B49","")
                .replace("1B4A","")
                .replace("1B4B","")
                .replace("1B4C","")
                .replace("1B4D","")
                .replace("1B4E","")
                .replace("1B4F","")
                .replace("1B50","0")
                .replace("1B51","1")
                .replace("1B52","2")
                .replace("1B53","3")
                .replace("1B54","4")
                .replace("1B55","5")
                .replace("1B56","6")
                .replace("1B57","7")
                .replace("1B58","8")
                .replace("1B59","9")
                .replace("1B5A","")
                .replace("1B5B","")
                .replace("1B5C","")
                .replace("1B5D",":")
                .replace("1B5E",",")
                .replace("1B5F",".")
                .replace("1B60","")
                .replace("1B61","")
                .replace("1B62","")
                .replace("1B63","")
                .replace("1B64","")
                .replace("1B65","")
                .replace("1B66","")
                .replace("1B67","")
                .replace("1B68","")
                .replace("1B69","")
                .replace("1B6A","")
                .replace("1B6B","")
                .replace("1B6C","")
                .replace("1B6D","")
                .replace("1B6E","")
                .replace("1B6F","")
                .replace("1B70","")
                .replace("1B71","")
                .replace("1B72","")
                .replace("1B73","")
                .replace("1B74","")
                .replace("1B75","")
                .replace("1B76","")
                .replace("1B77","")
                .replace("1B78","")
                .replace("1B79","")
                .replace("1B7A","")
                .replace("1B7B","")
                .replace("1B7C","")
                .replace("1B7D","")
                .replace("1B7E","")
                .replace("1B7F","")
                .replace("0020"," ");

        return text;
    }

    public Filter3(){

    }
}
