package com.example.testta;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

public class Filter1 {

    public String transliterasi(String text){

        try {
            String encde = URLEncoder.encode(text, "UTF-8");
            text=encde
                    .replace("%E1%AC%80","1B00")
                    .replace("%E1%AC%81","1B01")
                    .replace("%E1%AC%82","1B02")
                    .replace("%E1%AC%83","1B03")
                    .replace("%E1%AC%84","1B04")
                    .replace("%E1%AC%85","1B05")
                    .replace("%E1%AC%86","1B06")
                    .replace("%E1%AC%87","1B07")
                    .replace("%E1%AC%88","1B08")
                    .replace("%E1%AC%89","1B09")
                    .replace("%E1%AC%8A","1B0A")
                    .replace("%E1%AC%8B","1B0B")
                    .replace("%E1%AC%8C","1B0C")
                    .replace("%E1%AC%8D","1B0D")
                    .replace("%E1%AC%8E","1B0E")
                    .replace("%E1%AC%8F","1B0F")
                    .replace("%E1%AC%90","1B10")
                    .replace("%E1%AC%91","1B11")
                    .replace("%E1%AC%92","1B12")
                    .replace("%E1%AC%93","1B13")
                    .replace("%E1%AC%94","1B14")
                    .replace("%E1%AC%95","1B15")
                    .replace("%E1%AC%96","1B16")
                    .replace("%E1%AC%97","1B17")
                    .replace("%E1%AC%98","1B18")
                    .replace("%E1%AC%99","1B19")
                    .replace("%E1%AC%9A","1B1A")
                    .replace("%E1%AC%9B","1B1B")
                    .replace("%E1%AC%9C","1B1C")
                    .replace("%E1%AC%9D","1B1D")
                    .replace("%E1%AC%9E","1B1E")
                    .replace("%E1%AC%9F","1B1F")
                    .replace("%E1%AC%A0","1B20")
                    .replace("%E1%AC%A1","1B21")
                    .replace("%E1%AC%A2","1B22")
                    .replace("%E1%AC%A3","1B23")
                    .replace("%E1%AC%A4","1B24")
                    .replace("%E1%AC%A5","1B25")
                    .replace("%E1%AC%A6","1B26")
                    .replace("%E1%AC%A7","1B27")
                    .replace("%E1%AC%A8","1B28")
                    .replace("%E1%AC%A9","1B29")
                    .replace("%E1%AC%AA","1B2A")
                    .replace("%E1%AC%AB","1B2B")
                    .replace("%E1%AC%AC","1B2C")
                    .replace("%E1%AC%AD","1B2D")
                    .replace("%E1%AC%AE","1B2E")
                    .replace("%E1%AC%AF","1B2F")
                    .replace("%E1%AC%B0","1B30")
                    .replace("%E1%AC%B1","1B31")
                    .replace("%E1%AC%B2","1B32")
                    .replace("%E1%AC%B3","1B33")
                    .replace("%E1%AC%B4","1B34")
                    .replace("%E1%AC%B5","1B35")
                    .replace("%E1%AC%B6","1B36")
                    .replace("%E1%AC%B7","1B37")
                    .replace("%E1%AC%B8","1B38")
                    .replace("%E1%AC%B9","1B39")
                    .replace("%E1%AC%BA","1B3A")
                    .replace("%E1%AC%BB","1B3B")
                    .replace("%E1%AC%BC","1B3C")
                    .replace("%E1%AC%BD","1B3D")
                    .replace("%E1%AC%BE","1B3E")
                    .replace("%E1%AC%BF","1B3F")
                    .replace("%E1%AD%80","1B40")
                    .replace("%E1%AD%81","1B41")
                    .replace("%E1%AD%82","1B42")
                    .replace("%E1%AD%83","1B43")
                    .replace("%E1%AD%84","1B44")
                    .replace("%E1%AD%85","1B45")
                    .replace("%E1%AD%86","1B46")
                    .replace("%E1%AD%87","1B47")
                    .replace("%E1%AD%88","1B48")
                    .replace("%E1%AD%89","1B49")
                    .replace("%E1%AD%8A","1B4A")
                    .replace("%E1%AD%8B","1B4B")
                    .replace("%E1%AD%8C","1B4C")
                    .replace("%E1%AD%8D","1B4D")
                    .replace("%E1%AD%8E","1B4E")
                    .replace("%E1%AD%8F","1B4F")
                    .replace("%E1%AD%90","1B50")
                    .replace("%E1%AD%91","1B51")
                    .replace("%E1%AD%92","1B52")
                    .replace("%E1%AD%93","1B53")
                    .replace("%E1%AD%94","1B54")
                    .replace("%E1%AD%95","1B55")
                    .replace("%E1%AD%96","1B56")
                    .replace("%E1%AD%97","1B57")
                    .replace("%E1%AD%98","1B58")
                    .replace("%E1%AD%99","1B59")
                    .replace("%E1%AD%9A","1B5A")
                    .replace("%E1%AD%9B","1B5B")
                    .replace("%E1%AD%9C","1B5C")
                    .replace("%E1%AD%9D","1B5D")
                    .replace("%E1%AD%9E","1B5E")
                    .replace("%E1%AD%9F","1B5F")
                    .replace("%E1%AD%A0","1B60")
                    .replace("%E1%AD%A1","1B61")
                    .replace("%E1%AD%A2","1B62")
                    .replace("%E1%AD%A3","1B63")
                    .replace("%E1%AD%A4","1B64")
                    .replace("%E1%AD%A5","1B65")
                    .replace("%E1%AD%A6","1B66")
                    .replace("%E1%AD%A7","1B67")
                    .replace("%E1%AD%A8","1B68")
                    .replace("%E1%AD%A9","1B69")
                    .replace("%E1%AD%AA","1B6A")
                    .replace("%E1%AD%AB","1B6B")
                    .replace("%E1%AD%AC","1B6C")
                    .replace("%E1%AD%AD","1B6D")
                    .replace("%E1%AD%AE","1B6E")
                    .replace("%E1%AD%AF","1B6F")
                    .replace("%E1%AD%B0","1B70")
                    .replace("%E1%AD%B1","1B71")
                    .replace("%E1%AD%B2","1B72")
                    .replace("%E1%AD%B3","1B73")
                    .replace("%E1%AD%B4","1B74")
                    .replace("%E1%AD%B5","1B75")
                    .replace("%E1%AD%B6","1B76")
                    .replace("%E1%AD%B7","1B77")
                    .replace("%E1%AD%B8","1B78")
                    .replace("%E1%AD%B9","1B79")
                    .replace("%E1%AD%BA","1B7A")
                    .replace("%E1%AD%BB","1B7B")
                    .replace("%E1%AD%BC","1B7C")
                    .replace("%E1%AD%BD","1B7D")
                    .replace("%E1%AD%BE","1B7E")
                    .replace("%E1%AD%BF","1B7F")
                    .replace("+","0020");

            return text;

        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

        return text;
    }

    public Filter1(){

    }
}
